language: node_js
node_js:
  - '4'

before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codecov

script:
  - npm install
  - istanbul cover _mocha --report lcovonly -- -R spec && codecov

after_success:
